experiment_name: agent_test
n_seeds: 1

defaults:
  env:
    type: discrete
    grid_size: 10

  blow:
    interval: 40
    warning_duration: 10
    active_duration: 5
    width: 1
    num_lines: 2

  run:
    steps: 500

runs:
  - name: random
    agent:
      type: random

  - name: keyboard
    agent:
      type: keyboard