experiment_name: ice_blow_experiment
n_seeds: 5
start_seed: 0

defaults:
  env:
    type: discrete
    grid_size: 10

  blow:
    interval: 50
    warning_duration: 10
    active_duration: 5
    width: 1
    num_lines: 2

  run:
    steps: 2000

runs:
  - name: dqn
    agent:
      type: dqn

  # - name: td3
  #   agent:
  #     type: td3

  - name: random
    agent:
      type: random

  - name: keyboard
    agent:
      type: keyboard
